kind: Deployment
apiVersion: apps/v1
metadata:
  name: chatapp-backend
  namespace: chatapp
  labels:
    app: chatapp-backend
spec:
  selector:
    matchLabels:
      app: chatapp-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: chatapp-backend
      namespace: chatapp
    spec:
      containers:
      - name: chatapp-backend
        image: roni313233/chatapp-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5001"
        - name: MONGODB_URI
          value: "mongodb://root:admin@mongo:27017/chatapp?authSource=admin&retryWrites=true&w=majority"
        - name: JWT_SECRET
          value: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc2Mjg3MTM5MCwiaWF0IjoxNzYyODcxMzkwfQ.w7q8yVfQoUxccF-jAIqHz3W-qNcwGuRrcEPxdaMMa_g"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
            