apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chatapp
spec:
  selector:
    app: chatapp-backend
  type: ClusterIP
  ports:
  - name: backend
    protocol: TCP
    port: 5001
    targetPort: 5001 