apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chatapp
spec:
  selector:
    app: chatapp-frontend
  type: ClusterIP
  ports:
  - name: frontend
    protocol: TCP
    port: 80
    targetPort: 80 