apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: chatapp
spec:
  selector:
    app: mongo-deployment
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
